### ISSUE TITLE
FeaReq: Discord Server

### ISSUE THREAD

**Issue by Uniminin** [RXT0112/Zernit#105]
We need a place where we can discuss, share, help others. We need a ZERNIT discord server. Make it happen.

**Comment by Kreyren** [comment]
There is already:

![image](https://user-images.githubusercontent.com/11302521/79405190-01c81a80-7f94-11ea-89e9-fb160cbb1269.png)

Can you contrib it in `.github/README.md` ?

**Comment by Kreyren** [comment]
FWIW: Use sensible naming of issues next time

**Comment by Kreyren** [comment]
FWIW: You are also welcomed to make other communities and give me admin access to be considered as official.

**Comment by Uniminin** [comment]
@Kreyren https://i.imgur.com/bSBuIGf.png

**Comment by Kreyren** [comment]
Feel free to fix it i currently don't have a timeframe for it.
