### ISSUE TITLE
Feature: Interactive & Friendly.

### ISSUE THREAD

**Issue by Uniminin** [RXT0112/Zernit#26]
Add some cool features, make it friendly and interactive.

**Comment by renault24** [comment]
would be sweet

**Comment by Kreyren** [comment]
> Add some cool features

Elaborate on features and i will consider them and if possible their implementation is possible then i will support their implementation (compilation of this project will allow cherry-picking of wanted features)

> make it friendly and interactive.

next step in init phase is to develop some kind of foundation for GUI and currently i'm experimenting with method for logging with phylosophy to make messages understandable by 8yo kid and to output message that in case end-user can't interpret to diagnose the issue could be just parsed in github issues to be auto-solved through regex and logic.
